[mypy]
python_version = 3.14
show_error_codes = true
incremental = true
ignore_missing_imports = true
check_untyped_defs = true
# Definitive search path and package lock
mypy_path = custom_components:.
packages = hyxi_cloud_dev,tests
namespace_packages = false
explicit_package_bases = false
