name: "Close stale issues"

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight

permissions:
  contents: none

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443

      - uses: actions/stale@eb5cf3af3ac0a1aa4c9c45633dd1ae542a27a899 # v10.3.0
        with:
          # Number of days of inactivity before an issue becomes stale
          days-before-stale: 60

          # Number of days of inactivity before a stale issue is closed
          days-before-close: 7

          # Message to post when marking an issue as stale
          stale-issue-message: 'This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions!'

          # Message to post when closing a stale issue
          close-issue-message: 'This issue has been automatically closed due to inactivity.'

          # Label to apply when an issue is stale
          stale-issue-label: 'no-recent-activity'

          # Exempt issues with these labels from being marked stale
          exempt-issue-labels: 'pinned,security,confirmed'
